### ISSUE TITLE
我用/run_har2case接口无法生成最新的xx.json到testcase文件夹下

### ISSUE THREAD

**Issue by RanY-Luck** [BoxTester/httprunner_fastapi#1]
我用/run_har2case接口无法生成最新的xx.json到testcase文件夹下，
我解决的办法就是手动har2case xxx.har 生成后拖动到testcase下然后运行/run_pytest接口

**Comment by BoxTester** [comment]
> 我用/run_har2case接口无法生成最新的xx.json到testcase文件夹下， 我解决的办法就是手动har2case xxx.har 生成后拖动到testcase下然后运行/run_pytest接口

该方法是生成json内容，不是生成文件

**Comment by RanY-Luck** [comment]
那我如果把testcase下的requests.json删掉，然后重新执行/run_har2case的接口 他就没有那个json文件，也就没有那个json内容了，这点是让我很疑惑的

**Comment by BoxTester** [comment]
> 那我如果把testcase下的requests.json删掉，然后重新执行/run_har2case的接口 他就没有那个json文件，也就没有那个json内容了，这点是让我很疑惑的


该方法得到的结果是用作run_debug的入参使用的，不会直接生成文件，生成文件可直接使用har2case（这也说明该项目是提供对外接口的执行服务，run_har2case也是为了调用run_debug使用的）

**Comment by BoxTester** [comment]
可加本人飞书账号
![1](https://user-images.githubusercontent.com/37102283/219312769-c1a63b67-f1a8-46b8-854e-22f8f77614df.jpg)
